networks:
  phpinfo-2:
    internal: true
services: 
  phpinfo-2:
    deploy: 
      mode: replicated
      placement: 
        constraints: 
        - node.role == worker
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    expose:
    - 8080
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: wget -q --spider http://localhost:8080
      timeout: 1s
    image: rpozaisban/phpinfo-2:latest
    networks: 
    - phpinfo-2
    ports:
    - 8080:8080
version: "3.8"    
