name: CI
on: 
  push:
    branches: 
    - docker
jobs: 
  docker:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        set -x
        docker build -t test .
        docker run -d --name testcontainer test
        while true 
          do \
            sleep 10
            docker exec testcontainer ps | grep 'php -f index.php' && break
          done
        while true
          do \
            sleep 10
            docker logs testcontainer 2>& 1 | grep 'PHP .* Development Server .* started' && break 
          done      
  swarm:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        set -x
        #creo imagen image
        docker build -t terferre/phpinfo-2:testing .
        docker swarm init
        project=phpinfo-2
        compose=etc/swarm/manifests/${project}.yaml
        #sustituyo latest x testing y despliego con compose
        sed -i /image:/s/latest/testing/ ${compose}
        sed -i /node.role/s/worker/manager/ ${compose}
        #Despliegue en Openshift
        #oc apply -f ${compose}
        #despliegue en Kubernetes
        #kubectl apply -f ${compose}
        #desplioegue en swarm
        docker stack deploy -c ${compose} ${project}
        while true 
          do \
            sleep 10
            docker service ls | grep "${project}.*\([0-9]\)/\1" && break
          done
        while true
          do \
            sleep 10
            docker service logs ${project}_${project} 2>& 1 | grep 'PHP .* Development Server .* started' && break 
          done  
